//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonMVCv2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CustomerID { get; set; }
        [StringLength(40, MinimumLength = 2)]
        public string FirstName { get; set; }
        [StringLength(40, MinimumLength = 2)]
        public string LastName { get; set; }
        [StringLength(40, MinimumLength = 2)]
        public string Address1 { get; set; }
        [StringLength(40, MinimumLength = 2)]
        public string Address2 { get; set; }
        [StringLength(40, MinimumLength = 2)]
        public string City { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9]*$")]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
